name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install server tools
        run: |
          apt-get update
          apt-get install -y rsync

      - name: Install dependencies
        run: |
          npm install
          cd backend && npm install && cd ..
          cd frontend && npm install && cd ..

      - name: Build frontend
        env:
          FRONTEND_ENV: ${{ secrets.FRONTEND_ENV }}
        run: |
          cd frontend
          echo "$FRONTEND_ENV" > .env.production
          npm run build
          cd ..

      - name: Setup SSH for deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          cat >> ~/.ssh/config <<EOF
          Host prod
            HostName $SERVER_HOST
            User $SERVER_USER
            IdentityFile ~/.ssh/id_ed25519
            StrictHostKeyChecking no
          EOF

      - name: Add server to known_hosts
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
        run: |
          ssh-keyscan -H $SERVER_HOST >> ~/.ssh/known_hosts

      - name: Upload project files to server
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          DEPLOY_PATH: "/var/www/aeroecho"
        run: |
          rsync -avz --delete \
            --exclude=".git" \
            --exclude="node_modules" \
            --exclude="frontend/node_modules" \
            --exclude="backend/node_modules" \
            ./ $SERVER_USER@$SERVER_HOST:$DEPLOY_PATH

      - name: Install production deps on server
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          DEPLOY_PATH: "/var/www/aeroecho"
        run: |
          ssh prod "cd $DEPLOY_PATH/frontend && npm install --omit=dev"
          ssh prod "cd $DEPLOY_PATH/backend && npm install --omit=dev"

      - name: Write backend env on server
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          BACKEND_ENV: ${{ secrets.BACKEND_ENV }}
          DEPLOY_PATH: "/var/www/aeroecho"
        run: |
          ssh prod "echo \"$BACKEND_ENV\" > $DEPLOY_PATH/backend/.env"

      - name: Restart PM2 services
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          DEPLOY_PATH: "/var/www/aeroecho"
        run: |
          ssh prod "pm2 restart aeroecho-backend || pm2 start $DEPLOY_PATH/backend/ecosystem.config.js --only aeroecho-backend"
          ssh prod "pm2 restart aeroecho-frontend || pm2 start $DEPLOY_PATH/frontend/ecosystem.config.js --only aeroecho-frontend"
